tap "hashicorp/tap" 
tap "olets/tap"
tap "supabase/tap"

# replace basic commands with GNU/Linux version
brew "bash"
brew "coreutils"
brew "diffutils"
brew "findutils"
brew "ed"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "gzip"
brew "iproute2mac"

# utility commands
brew "awscli"
brew "ffmpeg"
brew "fzf"
brew "gifsicle"
brew "imagemagick"
brew "wget"
brew "git"
brew "neovim"
brew "tree"
brew "tmux"
brew "jq"
brew "yq"
brew "unzip"
brew "ghq"
brew "gh"
brew "mise"
brew "direnv"
brew "bat"
brew "git-delta"
brew "kubectl"
brew "kubectx"
brew "kubie"
brew "stern"
brew "lima"
brew "navi"
brew "git-secrets"
brew "act"
brew "mas"
brew "supabase/tap/supabase"
brew "hashicorp/tap/terraform"
brew "vercel-cli"

# zsh customize
brew "zsh-completions"
brew "zsh-autosuggestions"
brew "olets/tap/zsh-abbr"
brew "starship"
brew "zinit"

# fonts
cask "font-hack-nerd-font"

# GUI applications
cask "visual-studio-code"
cask "karabiner-elements"
cask "google-japanese-ime"
cask "1password"
cask "1password-cli"
cask "raycast"
cask "session-manager-plugin"
cask "wireshark"
cask "docker"
cask "arc"
cask "obsidian"
cask "notion"
cask "chromium"
cask "adobe-creative-cloud"
cask "cursor"
cask "figma"
cask "discord"
cask "iterm2"
cask "slack"
cask "zoom"
cask "obs"
cask "spotify"
cask "chatgpt"
cask "claude"

# App Store applications
mas "LINE", id: 539883307
mas "Whisper Transcription", id: 1668083311
